// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://moahyxpssmlqaqgvvmvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vYWh5eHBzc21scWFxZ3Z2bXZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NTkyMTksImV4cCI6MjA2NDIzNTIxOX0.LrFCFooodEK_JoL8WECyPRqQzXJO74hUVqO6neRpb9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);